create table join_applications (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text not null,
  age integer not null check (age >= 18),
  occupation text not null,
  motivation text not null,
  skills text,
  status text default 'pending' check (status in ('pending', 'under_review', 'approved', 'rejected')),
  submitted_at timestamp with time zone default now(),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Create index for faster queries
create index idx_join_applications_status on join_applications(status);
create index idx_join_applications_submitted_at on join_applications(submitted_at desc);

-- Enable Row Level Security (optional, if you want to secure the table)
alter table join_applications enable row level security;

-- Create policy to allow service role to insert (needed for the application)
create policy "Service role can insert applications" 
  on join_applications for insert 
  to service_role 
  with check (true);

-- Create policy to allow service role to select (needed for admin viewing)
create policy "Service role can select applications" 
  on join_applications for select 
  to service_role 
  using (true);