-- Create members table to track RAC numbers and user data
CREATE TABLE IF NOT EXISTS members (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  rac_number TEXT UNIQUE NOT NULL,
  email TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  phone TEXT,
  occupation TEXT,
  is_admin BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for faster queries
CREATE INDEX idx_members_rac_number ON members(rac_number);
CREATE INDEX idx_members_email ON members(email);
CREATE INDEX idx_members_user_id ON members(user_id);
CREATE INDEX idx_members_is_admin ON members(is_admin);

-- Link applications to members
ALTER TABLE join_applications 
ADD COLUMN IF NOT EXISTS rac_number TEXT UNIQUE,
ADD COLUMN IF NOT EXISTS rac_assigned_at TIMESTAMP WITH TIME ZONE;

-- Enable Row Level Security
ALTER TABLE members ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Service role can manage members" 
  ON members FOR ALL 
  TO service_role 
  USING (true) 
  WITH CHECK (true);

CREATE POLICY "Users can view their own member record" 
  ON members FOR SELECT 
  USING (auth.uid() = user_id OR is_admin);

CREATE POLICY "Admins can view all members" 
  ON members FOR SELECT 
  USING (
    EXISTS (
      SELECT 1 FROM members m 
      WHERE m.user_id = auth.uid() AND m.is_admin = true
    )
  );
